### ISSUE TITLE
Setup Discussion

### ISSUE THREAD

**Issue by jongfeel** [Joseph-Cha/JustFight_Client#1]
Settings에 보면 Features 항목 중에 마지막 항목에 Discussion이 있습니다.

이걸 체크하면 repository에 Discussion 탭이 생겨요.

차이점을 다시 말씀드리면

issue => 버그나 개선, 수정해야 할 사항에 관련된 논의
discussion => 일반 적인 질문/답변, 새로운 아이디어, 아무말 대잔치

**Comment by Joseph-Cha** [comment]
감사합니다~ Discussion 오픈 했고 곧 첫 글 올릴겠습니다!
