### ISSUE TITLE
테스트 코드 오류

### ISSUE THREAD

**Issue by Joseph-Cha** [Joseph-Cha/JustFight_Client#32]
![image](https://user-images.githubusercontent.com/75019048/111862375-56d89180-8998-11eb-89fa-9191b2233a37.png)

`            Assert.AreEqual(scene.name, "Main");
`

위와 같이 테스트 코드를 작성했는데 암만 해봐도 expected 값(scene.name)이 나옵니다ㅠㅠ

**Comment by jongfeel** [comment]
#29 에도 얘기했는데
Edit mode여서 그럴 수도 있다고 봅니다. 다른 방법으로 진행해봐야 할 것 같군요!
