### ISSUE TITLE
플레이어 이동 테스트 코드 작성 및 빈 오브젝트 생성

### ISSUE THREAD

**Issue by Joseph-Cha** [Joseph-Cha/JustFight_Client#47]
### 테스트 계획
10 프레임 동안 플레이어를 이동 시킨 후 해당 위치가 의도한 위치인지 여부를 테스트

### Detail
- Arrage
    - Player player
    - (Enum) curDir
    - Vecto3Int curPos
    - Vector3Int desPos
- Act
    - do( cur = Diretion.Left...) while(wait 10s)
- Assert
    - Assert.Equal(desPos, curPos)

**Comment by jongfeel** [comment]
이정도 적을 수 있으면 바로 테스트 코드를 작성하는 게 좋을 것 같아요.
