### ISSUE TITLE
Do working progress without pull request.

### ISSUE THREAD

**Issue by jongfeel** [Joseph-Cha/JustFight_Client#60]
11번째 미팅 때 논의했던 코멘트

https://github.com/Joseph-Cha/JustFight_Client/discussions/59#discussioncomment-1008062

그래서 별도의 리뷰가 필요할 경우에 pull request로 진행하고
review가 크게 상관 없는 작업, 리소스 맵핑, 캐릭터 애니매이션 과 같은 작업은
pull request 없이 단독으로 진행해야 뭔가 숙제검사 받듯이 진행되는 느낌이 없을 것 같습니다.

요렇게 한번 진행해 보시죠.

**Comment by Joseph-Cha** [comment]
좋은 방법인 것 같습니다!
말씀해주신 방법대로 우선 진행해볼게요 :D
